### PR TITLE
Spike-in can skip epilog if needed

### PR DESCRIPTION
**Pull request by vreuter**

### CODE REVIEW

**Review by nsheff — COMMENTED** [review]
ok, would you want to make all the epilog commands *not* nofail=True if you do this way? Because the exceptions are caught by this extra layer, so then it would only try until it hit something that failed and not run the other spikein components??

have you tested this on a sample that doesn't have spike-in to make sure the pipeline says 'success'?

**Comment by vreuter** [comment]
> ok, would you want to make all the epilog commands _not_ nofail=True if you do this way?

Yes, but then any exception that's not a `EpilogPretestError` would cause a failure, and it sounded like that's _not_ what you wanted.

> have you tested this on a sample that doesn't have spike-in to make sure the pipeline says 'success'?

Multiple neuron samples succeeded; did those have spike-in? That was a few commits ago, though. What's your suggestion for a sample to test?

**Comment by nsheff** [comment]
why don't you just catch all errors instead?

you could try a sample from here: ${SRAMETA}/GSE86952/GSE86952_config.yaml

the bam conversion is underway right now so it will take an hour or so before all the files are there. but you might be able to find one.

**Comment by vreuter** [comment]
The alternatives seem to be:
1. Catch the specific error and keep commands contained in that block `nofail=True` (current)
2. Catch all exceptions and make the contained commands `nofail=False` (possible alternative)

In either case, the desired/intended effect would be that a spike-in processing error doesn't fail the pipeline.
The mechanical difference appears to me to be in how the error is triaged and communicated.
1. Defer to the methylation pipeline only when the exception is related to the epilog preconditions; use `pypiper` infrastructure otherwise.
2. Defer to the methylation pipeline in all cases.

The material difference seems to be extra control over message detail, afforded by the option you suggested (2). I think that's good, but we could also do that upstream, in `pypiper`, by printing more error detail in `PipelineManager._triage_error`

**Comment by vreuter** [comment]
All that's to say that I don't really have a preference; they seem virtually equivalent to me, with a slight benefit in the second that'd be even more beneficial if implemented in `pypiper` rather than here.

**Comment by vreuter** [comment]
> the bam conversion is underway right now so it will take an hour or so before all the files are there. but you might be able to find one.

I don't understand what the second sentence means. You're suggesting to look now, or in an hour?

**Comment by nsheff** [comment]
Ok I'm not really know what the term 'triage error` means so I don't really follow your logic. I'm all for the 'best' solution but don't see how to put this logic into pypiper.

> You're suggesting to look now, or in an hour?
I've gone ahead and submitted a test sample.

/sfs/lustre/allocations/shefflab/processed/GSE86952/submission/rrbs_AML_blast_322.sub

**Comment by vreuter** [comment]
> Ok I'm not really know what the term 'triage error` means so I don't really follow your logic. I'm all for the 'best' solution but don't see how to put this logic into pypiper.
> 
> > You're suggesting to look now, or in an hour?
> > I've gone ahead and submitted a test sample.
> 
> /sfs/lustre/allocations/shefflab/processed/GSE86952/submission/rrbs_AML_blast_322.sub

That doesn't have an epilog flag

**Comment by vreuter** [comment]
@nsheff you have one job running. Is that the one for /sfs/lustre/allocations/shefflab/processed/GSE86952/submission/rrbs_AML_blast_322.sub? If so, do you want to cancel since it doesn't have the epilog flag?

**Comment by nsheff** [comment]
doh. it completed successfully, thought, that's good :). Also apparently it successfully aligned some things to spike-in, even though it didn't have a spike in. I guess I'll try another.

**Comment by nsheff** [comment]
i had also run a sample with epilog that compelted successfully.

**Comment by nsheff** [comment]
also the epilog flag is not what we're testing here, it's the spike in alignment, right?

**Comment by vreuter** [comment]
`bismark` bails on the deduplication attempt when the alignment file is empty, and `epilog` is the first thing that tries to use that deduplication result, so I think the epilog flag is important for validation.

**Pull request merged**
