### PR TITLE
Pep2

### PR DESCRIPTION
**Pull request by stolarczyk**
@j-lawson, this includes the new pipeline interface format, which probably should have been released a long time ago

### CODE REVIEW

**Comment by vreuter** [comment]
Cool! I won't be able to review until next week but don't want to hold this up if you want to merge it in before then.

**Comment by nsheff** [comment]
I think there were 1 or two last things that were holding me up as not quite finished on this. I need to check on on where we stand on:

1. is this using the latest refgenie Python API correctly? @stolarczyk can you check?
2. This pipeline needs a special kind of format for fasta files where each chrom is in its own file. I had started to write a refgenie recipe to do this, which is on a branch: https://github.com/refgenie/refgenie/tree/split_fasta -- I was debating whether to go with that, or to try to move on from the software that requires it...
3. I had been starting to work with Vince on getting the latest epilog integrated in here. I've dropped the ball on that. @vreuter what are your thoughts? Is epilog in a state ready for release yet?

**Comment by stolarczyk** [comment]
> is this using the latest refgenie Python API correctly?

yes, it uses `seek` method for path retrieval which is the correct way to do it

**Comment by stolarczyk** [comment]
And just to be clear, I'm not in a rush to release this. John contacted me to troubleshoot a looper submission issue, which turned out to be an outdated piface on `master`

**Comment by j-lawson** [comment]
Yes, I need to process some RRBS samples whether it is with the new version or the old version. I guess if I use the old version I could probably use the old version of other software life PEP by using bulker, right?

**Comment by nsheff** [comment]
Closing in favor of #50

**Pull request closed without merging**
