### PR TITLE
Modularized downstream processing

### PR DESCRIPTION
**Pull request by vreuter**
Functional compartmentalization processing/analysis downstream of `bismark` /  `bsmap` affords us greater target specificity so that in case of failure our jobs will redo less work.
- [x] Check #29

### CODE REVIEW

**Comment by nsheff** [comment]
Ok I've spent some time digging into this now. It's fine with me, but just consider this viewpoint:

When I look at this, I see about 250 lines of code dedicated to producing epilog commands (functions called `make_main_epi_cmd`, `get_epilog_full_command`,  `get_epilog_union_command`, `get_epilog_strand_merge_command`, and others).

My first reaction to this as an outside is, 'what is so complicated about running this particular tool?'. I haven't had time to try to understand what each function does and I'm sure you have good reasons for all of them. But is there any way we can outsource some of this complexity into epilog itself? For example, the `run_main_epi_pipe` function kind of goes against the grain of the rest of the pipeline, which produces commands and then runs them with `pm.run`.

If epilog is really doing something that essentially warrants its own sub-pipeline, that's fine. But now might be a good time to just step back and ask if any of this can be handled in epilog itself, so that the pipeline command is done in the same was as all the other pipeline commands. I think that would improve epilog and this pipeline.

As a secondary thought -- I noticed `ProgSpec` here. I think `ProgSpec` is something that should be in pypiper, perhaps? We already implemented some resource functionality in `NGSTk`, is it possible that does the same thing? I can't see from a first reading what this is doing.

If after considering these things you still think this is the best way, then go for it, I approve.

**Comment by nsheff** [comment]
I think after reading some of the issues I'm getting a better feel for what you're trying to accomplish. I think it's a good idea in general -- assuming epilog is the longest part of the pipeline. 

Maybe my concern would be addressed by keeping it the way you have it, but just maintaining the style of building of commands and running with `pm.run` in the main method like the rest of the pipeline, as a compromise.

**Comment by vreuter** [comment]
My first reaction when looking at previous versions was, "why is there so much repetition?" To change any one aspect of any portion, we typically had to update at least 2 (`rrbs` and `wgbs`) and often 4 (actual data file + spike-in file) for each. This made maintenance and evolution of code more tedious and error-prone. To me, homoegeneity of style isn't a reason to move back in that direction. If anything, I'd do similar generalization of functional blocks that are shared between the pipelines.

**Comment by vreuter** [comment]
To me, a "pipeline" is about assembling building blocks; `epilog` is its own unit, so it makes sense for the main method of each pipeline to treat it as such--each main method is a user of the tool that should be able to treat it mostly in black-box fashion, interacting with it minimally while still getting full functionality.

Similar to why something like `ngstk` is useful -- I don't want to have to know every flag for things like `samtools` and `bowtie2` and `macs`; suitably named functions that pre-populate those parameters help keep main methods of programs that use them cleaner and more readable. I don't see a great deal of difference here.

**Comment by nsheff** [comment]
I hadn't thought about the rrbs/wgbs problem. In many ways though they are quite different (like, they use different aligners, for example), and there originally wasn't anything shared between them, so they were totally independent.

**Comment by nsheff** [comment]
> To me, a "pipeline" is about assembling building blocks; 

Got it. Ok I'm on board. I think I should view this as ultimately moving everything into this format, right? Basically I think of this as upgrading the way the pipelines work, but piecemeal. So eventually we should work toward moving all the chunks into this approach, but for now it's fine if we have some heterogeneity.

I was going to test it but unfortunately I didn't get a chance, and I won't be able to actually test it until next week. So if you're ready for this to be a `v0.3` then go for it.

**Comment by nsheff** [comment]
@vreuter Are you planning to merge this in soon? I'm ready to try this on a real project,

**Comment by vreuter** [comment]
Sorry, I'd missed the "go for it" message from last week. Yeah this is about ready; I will try to merge later today.

**Pull request merged**
