### PR TITLE
Dark sequencing, custom downstream analysis

### PR DESCRIPTION
**Pull request by vreuter**
RRBS samples have now completed successfully for me. We will see about WGBS, but things seem ready for a new `master` version

### CODE REVIEW

**Comment by j-lawson** [comment]
Cool. I don't have any comments but thanks!

**Comment by vreuter** [comment]
Depends now on https://github.com/databio/pypiper/pull/96

**Comment by nsheff** [comment]
> Depends now on [databio/pypiper#96](https://github.com/databio/pypiper/pull/96)

Ok, can we keep it backwards compatible easily so it will work with previous versions of pypiper? I was going to release this soon...

**Comment by nsheff** [comment]
is this ready to be merged for you?

**Comment by vreuter** [comment]
Not quite; I want to adjust it now for the 0.10 version.

**Comment by nsheff** [comment]
ok.

**Pull request merged**
